[package]
authors = ["'TorvalHG' <'tpeyronel@gmail.com'>"]
edition = "2018"
name = "ash_sandbox"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.0"
ash = "0.35.1"
ash-window = "0.9.0"
bitflags = "1.3.2"
bus = "2.2.3"
chrono = "0.4.19"
const-cstr = "0.3.0"
enum-map = "2.0.0"
env_logger = "0.9.0"
gltf = "0.16.0"
hashbrown = "0.12.0"
imgui = "0.8.2"
imgui-rs-vulkan-renderer = {git = "https://github.com/TorvalHG/imgui-rs-vulkan-renderer"}
imgui-winit-support = "0.8.2"
log = "0.4.14"
memoffset = "0.6.1"
nalgebra = "0.25.4"
nalgebra-glm = "0.11.0"
serde = {version = "1.0.133", features = ["derive"]}
serde_json = "1.0.75"
shrev = "1.1.1"
slotmap = "1.0.2"
specs = {version = "0.17.0", features = ["specs-derive"]}
stb_image = "0.2.3"
tps_counter = {path = "../tps_counter"}
vk-mem = {path = "../rust/vk-mem"}
winit = "0.25.0"

[profile.dev.package."*"]
opt-level = 3
