pub const SHADER_RESOURCE_WORLD_MATRICES: &'static str = "WORLD_MATRICES";
pub const SHADER_RESOURCE_WORLD_LIGHTS: &'static str = "WORLD_LIGHTS";
pub const SHADER_RESOURCE_BILLBOARD_DATA: &'static str = "BILLBOARD_DATA";
pub const SHADER_RESOURCE_SKYBOX: &'static str = "SKYBOX";
pub const SHADER_RESOURCE_MATERIAL_DATA: &'static str = "MATERIAL_DATA";
pub const SHADER_RESOURCE_MATERIAL_DIFFUSE_TEXTURE: &'static str = "MATERIAL_DIFFUSE_TEXTURE";
pub const SHADER_RESOURCE_MATERIAL_SPECULAR_TEXTURE: &'static str = "MATERIAL_SPECULAR_TEXTURE";
pub const SHADER_RESOURCE_OBJECT_MATRICES: &'static str = "OBJECT_MATRICES";
